[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/klyvo-tab-v14*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
